name: Run Fast Scan 

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '11'

      - name: Run application
        run: java -jar fastScan.jar

