name: Run Fast Scan

on:
  push:
    branches:
      - main

jobs:
  FastScan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull docker image
        run: docker pull castimaging/fast-scan-java-cli

      - name: Run Fast Scan
        run: |
           echo "GIT_FOLDER_NAME=$(basename ${GITHUB_WORKSPACE})"
           docker run --rm -v $(pwd):/fastScan/sourceCode castimaging/fast-scan-java-cli /fastScan/sourceCode --appName=${GIT_FOLDER_NAME}
