name: Run Fast Scan

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pull docker image
        run: docker pull castimaging/fast-scan-java-cli

      - name: Run docker container
        run: |
          cd ${{ github.workspace }}
          git_folder = $(basename "$(git rev-parse --show-toplevel)")
          docker run -v $(pwd):/fastScan/sourceCode castimaging/fast-scan-java-cli /fastScan/sourceCode --appName git_folder


