name: Run Fast Scan 

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3.10.0
        with:
          java-version: '17'

      - name: Run application
        run: java -jar testcarl.jar https://github.com/bhawansh-bns/CRMModernization/ https://github.com/bhawansh-bns/CRMModernization/scans

