name: Run Fast Scan 

on:
  push:
    branches:
      - main

jobs:
  GithubContextFile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Login to docker
        uses: docker/login-action@v1
        with: 
          username: searaph
          password: password@123

      - name: Pull docker image
        run: docker pull searaph/testfastscan:latest
      
      - name: Run docker container
        run: |
          echo "${{ github.context }}" > github_context.txt
          docker run -v $(pwd):/fastScan/sourceCode searaph/testfastscan:latest /fastScan/sourceCode --githubContext github_context.txt

